### ISSUE TITLE
Wie Webinterface ohne Login nutzen

### ISSUE THREAD

**Issue by youtubegameos** [maxibanki/YoutubeWebinterface#11]
Hey! Wie ist es möglich, dass das Webinterface ohne Login auf Sinus funktioniert? Habe selber schon etwas rumprobiert, kahm aber nie zum Ergebnis. Wäre echt nett von dir, wenn du mir helfen könntest. 
Ich würde es gerne ohne login versuchen, da ich es für alle meine User frei zugänglich haben möchte;) 

Du kannst mich gerne unter Insta: game.os oder unter der Email kontakt@game-os.de

LG Marvin von #Game OS

**Comment by irgendwr** [comment]
Das ist momentan nicht möglich.

**Comment by mxschmitt** [comment]
Hallo,
wo willst du die YouTube Videos dann abspielen?
Weil somit herrscht ja dann keine Verbindung mehr zum Sinusbot, auf welchem zum einen die Einstellungen (API Key, Permission handling) sowie die eigentlichen YouTube Videos abgespielt werden sollen.

Am 18. September 2017 17:23:39 schrieb youtubegameos <notifications@github.com>:
Hey! Wie ist es möglich, dass das Webinterface ohne Login auf Sinus funktioniert? Habe selber schon etwas rumprobiert, kahm aber nie zum Ergebnis. Wäre echt nett von dir, wenn du mir helfen könntest.
Ich würde es gerne ohne login versuchen, da ich es für alle meine User frei zugänglich haben möchte;)
Du kannst mich gerne unter Insta: game.os oder unter der Email kontakt@game-os.de [mailto:kontakt@game-os.de]
LG Marvin von #Game OS

**Comment by youtubegameos** [comment]
Ist ja irgendwie schon logisch das ein Konto auch wegen den rechten benötigt wird. Aber ist es nicht möglich irgendwo diese Anmeldedaten in den code reinzuschreiben, so dass egal wer diese Seite aufruft automatisch angemeldet wird.

**Comment by irgendwr** [comment]
Nein, das ist nicht möglich, wie gesagt.
Die Seite ist nur angemeldet aufrufbar, das ist so vom sinusbot festgelegt, das können wir nicht ändern.

**Comment by youtubegameos** [comment]
Und Warum geht das bei anderen Scripts?

**Comment by irgendwr** [comment]
Und die wären?

**Comment by youtubegameos** [comment]
SinusBot Stream master und ts3 bot wi master 
Bei denen ist es möglich in die Scripts anmeldedaten für sinusbot einzugeben und Mann wird automatisch eingeloggt
