### ISSUE TITLE
Youtube Webinterface nicht aufrufbar

### ISSUE THREAD

**Issue by eliasbnr** [maxibanki/YoutubeWebinterface#12]
Hallo,

Ich habe ein Problem mit dem Youtube Webinterface.
Ich habe das script aktiviert und habe meinen Youtube Api key eingegeben, sobald ich jedoch auf die Webinterface Seite gehe werde ich immer zurück geleitet

**Comment by mxschmitt** [comment]
Hallo,
hast du das Script aktiviert? Wenn ja, kann es sein, dass dein Browser es cached. Versuche es doch dann bitte mal in einem Inkognito tab. :)

**Comment by eliasbnr** [comment]
Ja, Ich habe das Script aktiviert, jedoch funktioniert es auch nicht in einem Inkognito tab :/

**Comment by mxschmitt** [comment]
Hast du den `youtube` Ordner mit in deinem `scripts` Ordner kopiert?

**Comment by eliasbnr** [comment]
Ja das habe ich.

**Comment by eliasbnr** [comment]
![scripts](https://user-images.githubusercontent.com/30735061/33223346-ceb2f088-d15e-11e7-84ec-80a06e65a0d6.PNG)

**Comment by mxschmitt** [comment]
Welche Bot version verwendest du? Ich würde mir gern das Problem mal selbst anschauen, komme dazu doch bitte mal auf den `sinusbot.com` teamspeak.

**Comment by eliasbnr** [comment]
In Welchen Channel soll ich denn gehen?

**Comment by mxschmitt** [comment]
Nach Rücksprache mit dem Entwickler versuche doch bitte mal auf die neuste Version zu updaten. Dann sollte das Problem sich behoben haben.

**Comment by mxschmitt** [comment]
@Rubmcraft  Hat sich noch etwas ergeben oder funktioniert es jetzt? Weil dann würde ich das Issue schließen.

**Comment by eliasbnr** [comment]
Ja es hatte sich schon vor dem Update was getan, nach einem Neustart vom Bot hat das Webinterface wieder geklappt.
