### ISSUE TITLE
Can't access page /script/youtube

### ISSUE THREAD

**Issue by superhize** [maxibanki/YoutubeWebinterface#14]
[Short description of problem here]
I can't browse <url>/script/youtube, that get me to the main page of sinusbot

**Reproduction Steps:**

[First Step]
[Second Step]
[Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Sinusbot version: SinusBot 0.11.0-8e5f1a2
**OS and version:** Debian 8
**Used Browser and version:** Firefox Quantum

**Browser Console Logs:**
La connexion avec http://ts.hize.me:8087/api/v1/events?stoken=uQHwuHsiaSI6ImZkYmJmYjY4LTY4MmItNDA1My05YWU4LTJiNGI4ZDc4ZGI4NSIsImIiOiIyMDRhMTkzMC01YTg2LTQ3MDYtOTQ0MC0xY2Y3NWEwZGNhNjciLCJ1IjoiYWRtaW4iLCJ0IjoxNTE4MTE1NDYwLCJzIjoiMzYwZDYzMDU3YjhhN2UxNWI3MDYyYjE5Y2UyYzU1YjVkZjNjYmE4MmY0YTZlMDEyZDRhNGIzYzU5YzgyYTMyMSJ9 a été interrompue pendant le chargement de la page.

**Diagnostic **
==========================================================
SINUSBOT RELATED
SYSTEM INFORMATION
 - Operating System: Debian GNU/Linux 8.10 (jessie)
 - Kernel: Linux 4.4.49-1-pve x86_64
 - Load Average: 0.44 0.46 0.52
 - Uptime: 11 days, 0 hours, 13 minutes, 23 seconds
 - OS x64 check: OK
 - OS Updates: 0 (well done!)
 - OS Missing Packages: None
 - OS APT Last Update: 09.02.2018 04:27:59 CET +01:00:00
 - SHELL LOCALE LANG: C
 - Bot Start Script: found at /etc/init.d/sinusbot [perms: 755]
 - DNS resolution check: www.sinusbot.com resolved to 104.18.40.220 -> OK
 - HTTPS check with IPv4 mode: SUCCESS [Connection was established to www.sinusbot.com, CODE #200]
 - HTTPS check with IPv6 mode: IGNORE
 - CPU:
    Architecture:          x86_64
    CPU(s):                8
    Thread(s) per core:    2
    Core(s) per socket:    4
    Socket(s):             1
    Model name:            Intel(R) Xeon(R) CPU E5-1630 v4 @ 3.70GHz
    CPU MHz:               3637.417
    Virtualization:        VT-x
 - RAM: 1016.65 MB/1.00 GB in use (99%)
 - SWAP: 0 B/0 B in use (0%) (SWAP disabled)
 - DISK: 4.70 GB/17.58 GB in use (26%)
 - Package versions:
   + libglib: 2.42.1-1+b1

BOT INFORMATION
 - Status: running (PIDs: 2591 2590, User: Sinus sinusbot)
 - Webinterface: port locally reachable (Port: 8087)
 - Binary: /opt/sinusbot/sinusbot
 - Binary Info: MD5 Hash: f59b51a628eee417d53f6560e6365a09, Perms: 755, User: sinusbot
 - Version: 0.11.0-8e5f1a2
 - TS3 Plugin: installed (md5 hash match)
   - Bot Plugin: ce7bcdef6f438182b7c0d7dee8742510
   - TS3 Client: ce7bcdef6f438182b7c0d7dee8742510
 - Config:
   - LogLevel = 3
   - TS3Path = /opt/sinusbot/teamspeak3-client/ts3client_linux_amd64 (Version 3.1.8)
   - YoutubeDLPath = /opt/sinusbot/youtube-dl (does exist, version: 2018.02.08)
 - Installed scripts: AFK_Mover_(AwayMuteDeafIdle).js; Animated_Nickname.js; Digital_Clock.js; RankCSGO.js; Support.js; Youtube_Search.js; advertising.js; alonemode.js; bookmark.js; followme.js; norecording.js; rememberChannel.js; welcome.js; youtube.js

TIME INFORMATION
 - Time (local): 09.02.2018 16:43:45 CET +01:00:00
 - Time (remote): 09.02.2018 16:43:45 CET +01:00:00
 - Time (difference): 0 secs (Time diff less than 2 secs. Good.)
 - Timezone: Europe/Paris

OTHER INFORMATION
 - TeamSpeak 3 Version: 3.1.8
 - youtube-dl Version: 2018.02.08
 - DiagScript Version: 0.7.0
==========================================================

**Comment by mxschmitt** [comment]
Hi,

That's a know problem. In general that's a cause of your browser cache, try to clear it. If that doesn't work, try to access it by using an ikgnito tab or other browser.

Best regards

Max

**Comment by superhize** [comment]
Hi,

i tryed to clear cache, that doesn't work, same in a new browser.

Maybe because its red ? http://hize.me/i/rIUA

**Comment by mxschmitt** [comment]
Can you try to click onto the red text?

**Comment by superhize** [comment]
That try to go on /scripts/youtube, but redirect to the main page
