### ISSUE TITLE
No Youtube Key

### ISSUE THREAD

**Issue by ghost** [maxibanki/YoutubeWebinterface#15]
Even though I submitted my key in the interface, I still get the error. I'm using the "YouTube Data API v3".
```
2018-07-09T22:48:25-07:00 youtube :102 No Youtube API Key set.
2018-07-09T22:48:25-07:00 youtube :49 YTWeb Webinterface Ready
```

**Sinusbot version:** SinusBot 0.13.37-9791176

**Comment by mxschmitt** [comment]
Have you pressed the save button in the script settings?

**Comment by ghost** [comment]
Yes..

**Comment by mxschmitt** [comment]
I have tested it locally and it works without any problems. Check that you have set the key in the script settings. Then reload the YouTube Webinterface. If it's not working provide us the log from your's Browser JavaScript console.

**Comment by mxschmitt** [comment]
Closed because of no response.

**Comment by olokos** [comment]
I'm having the same issue. I think that even though the API keys are inserted and being used there's still warning remaining in logs.
https://i.gyazo.com/339935854c14f06aab7d212bd1a1bb67.png
