### ISSUE TITLE
Script not loading

### ISSUE THREAD

**Issue by lbenicio** [maxibanki/YoutubeWebinterface#19]
The script is not loaded
**Reproduction Steps:**

[First Step]
Installed as specified on sinubot forum thread
[Second Step]
Ob bot start got an error

**Expected behavior:**
script should load

**Observed behavior:**
the script did not load

**Sinusbot version:** 0.14.3-0e747fd
**OS and version:** ubuntu x64
**Used Browser and version:** 73.0.3683.27

**Browser Sinusbot Logs:**
2019/02/14 23:32:37 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin youtube.js
2019/02/14 23:32:37 [GENERAL/SCRIPTS] WARN   Could not parse script youtube.js: (anonymous): Line 39:5 Invalid left-hand side in assignment (and 93 more errors)

**Diagnostic **
==========================================================
SINUSBOT RELATED
SYSTEM INFORMATION
 - Operating System: Ubuntu 16.04.5 LTS
 - Kernel: Linux 4.4.0-134-generic x86_64
 - Load Average: 0.28 0.21 0.20
 - Uptime: 166 days, 17 hours, 7 minutes, 4 seconds
 - OS x64 check: OK
 - OS Updates: 60 (updates available!)
 - OS Missing Packages: None
 - OS APT Last Update: 14.02.2019 22:10:56 -02 -02:00:00
 - SHELL LOCALE LANG: en_US.UTF-8
 - Bot Start Script: not found
 - DNS resolution check: www.sinusbot.com resolved to 104.28.15.74 -> OK
 - HTTPS check with IPv4 mode: SUCCESS [Connection was established to www.sinusbot.com, CODE #200]
 - HTTPS check with IPv6 mode: IGNORE
 - CPU:
    Architecture:          x86_64
    CPU(s):                1
    Thread(s) per core:    1
    Core(s) per socket:    1
    Socket(s):             1
    Model name:            Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    CPU MHz:               2199.998
    Virtualization:        VT-x
    Hypervisor vendor:     KVM
    Virtualization type:   full
 - RAM: 569.10 MB/992.19 MB in use (57%)
 - SWAP: 170.94 MB/1.99 GB in use (8%)
 - DISK: 11.91 GB/24.05 GB in use (49%)
 - Package versions:
   + libglib: 2.48.2-0ubuntu4.1

BOT INFORMATION
 - Status: not running
 - Webinterface: port locally not reachable (Port: 8087)
 - Binary: /opt/sinusbot/sinusbot
 - Binary Info: MD5 Hash: 457224ee75d8a25d64eab6fc7465cd48, Perms: 755, User: sinusbot
 - Version: 0.14.3-0e747fd
 - TS3 Plugin: installed (md5 hash match)
   - Bot Plugin: 9463787dd59286dea7a4a284409993c3
   - TS3 Client: 9463787dd59286dea7a4a284409993c3
 - Config:
   - LogLevel = 3
   - TS3Path = /opt/sinusbot/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64 (Version 3.1.10)
   - YoutubeDLPath = not set (does exist anyway, version: 2018.10.05)
 - Installed scripts: advertising.js; alonemode.js; bookmark.js; Channel_Description_Changer.js; followme.js; norecording.js; Random_GIFs.js; rememberChannel.js; welcome.js; youtube.js; Youtube_Search.js; YT-search.js

TIME INFORMATION
 - Time (local): 14.02.2019 23:37:34 -02 -02:00:00
 - Time (remote): 14.02.2019 23:37:34 -02 -02:00:00
 - Time (difference): 0 secs (Time diff less than 2 secs. Good.)
 - Timezone: America/Sao_Paulo

OTHER INFORMATION
 - TeamSpeak 3 Version: 3.1.10
 - youtube-dl Version: 2018.10.05
 - DiagScript Version: 0.7.1
==========================================================

**Comment by mxschmitt** [comment]
You need to update to SinuBot version 1.0.0.

**Comment by lbenicio** [comment]
i just download the current version from the website and unpacked it. and it says is  0.14.3-0e747fd. how could i use sinusbot verison 1.0? @mxschmitt

**Comment by lbenicio** [comment]
i just check at forum and it says at version: SinusBot Beta 0.14.3-0e747fd

where do i find the version 1.0?

**Comment by irgendwr** [comment]
![forum](https://user-images.githubusercontent.com/17804578/52877843-74a0f000-315b-11e9-86d8-86babae5b34a.png)

https://forum.sinusbot.com/resources/internal-beta.1/
There is a detailed guide on the page on how to update.
