### ISSUE TITLE
Enqueue does not function as intended.

### ISSUE THREAD

**Issue by adambh** [maxibanki/YoutubeWebinterface#2]
`TypeError: 'qyt' is not a function at <anonymous>:17:13 at EventDispatcher (<anonymous>:136:69) at Event (<anonymous>:117:71) at <unknown>`

**Comment by mxschmitt** [comment]
For the Webinterface you need the latest Beta version

**Comment by JonasBoegle** [comment]
We already told you in the forum that you should update your Sinusbot.

**Comment by irgendwr** [comment]
@white-energy What version do you have? If you need help updating feel free to ask us or other people on the forum.

**Comment by adambh** [comment]
Well, i've had suspicions that my version was kinda outdated even if it was 0.9.12.. so when i found out there's a 0.9.12.2 and once i updated to it, the issue was solved.
To be honest, i had no idea the latest beta was required.
Thank you.
