### ISSUE TITLE
not playing videos

### ISSUE THREAD

**Issue by lbenicio** [maxibanki/YoutubeWebinterface#20]
[Short description of problem here]
The video enque but no plays with !playlist and if clicked on play at webinterface it says that it will plays but nothing happens
**Reproduction Steps:**
1. download Sinusbot: 1.0.0-alpha.6-a47ac17
2. setup a new bot
3. download latest youtube by: https://github.com/mxschmitt/YoutubeWebinterface/archive/master.tar.gz
4. try to start a video

**Expected behavior:**
it should start playing

**Observed behavior:**
it plays won't play neither on webinterface nor playlist command

**Sinusbot version:** 1.0.0-alpha.6-a47ac17
**OS and version:** Ubuntu 18 LTS
**Used Browser and version:** chrome

**Browser Console Logs:**
***Chrome:***
none

 1. Press `Ctrl + Shift + I` at the same time in a Browser window
 2. Select in the appearing menu `Console`
 3. Reload the page using `Ctrl + Shift + R`
 4. Copy might be appearing errors into the issue with ````
no erros

**Diagnostic **
Execute the script on [this page](https://forum.sinusbot.com/threads/diagsinusbot-sh-sinusbot-diagnostic-script.831/#post-4418) and post the output here.

==========================================================
SINUSBOT RELATED
SYSTEM INFORMATION
 - Operating System: Ubuntu 16.04.5 LTS
 - Kernel: Linux 4.4.0-134-generic x86_64
 - Load Average: 0.14 0.25 0.25
 - Uptime: 188 days, 13 hours, 41 minutes, 25 seconds
 - OS x64 check: OK
 - OS Updates: 69 (updates available!)
 - OS Missing Packages: None
 - OS APT Last Update: 08.03.2019 05:08:37 -03 -03:00:00
 - SHELL LOCALE LANG: en_US.UTF-8
 - Bot Start Script: not found
 - DNS resolution check: www.sinusbot.com resolved to 104.28.14.74 -> OK
 - HTTPS check with IPv4 mode: SUCCESS [Connection was established to www.sinusbot.com, CODE #200]
 - HTTPS check with IPv6 mode: IGNORE
 - CPU:
    Architecture:          x86_64
    CPU(s):                1
    Thread(s) per core:    1
    Core(s) per socket:    1
    Socket(s):             1
    Model name:            Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    CPU MHz:               2199.998
    Virtualization:        VT-x
    Hypervisor vendor:     KVM
    Virtualization type:   full
 - RAM: 659.31 MB/992.19 MB in use (66%)
 - SWAP: 95.92 MB/1.99 GB in use (4%)
 - DISK: 11.97 GB/24.05 GB in use (49%)
 - Package versions:
   + libglib: 2.48.2-0ubuntu4.1

BOT INFORMATION
 - Status: running (PIDs: 8743 8742, User: sinusbot)
 - Webinterface: port locally reachable (Port: 8087)
 - Binary: /opt/sinusbot/sinusbot
 - Binary Info: MD5 Hash: cc7e9b1c61045377b221302a86be605e, Perms: 755, User: sinusbot
 - Version: 1.0.0-alpha.6-a47ac17
 - TS3 Plugin: installed (md5 hash match)
   - Bot Plugin: 59c9a688307aa73af9573029a7625fc5
   - TS3 Client: 59c9a688307aa73af9573029a7625fc5
 - Config:
   - LogLevel = 3
   - TS3Path = /opt/sinusbot/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64 (Version 3.2.3)
   - YoutubeDLPath = not set (does exist anyway, version: 2019.03.09)
 - Installed scripts: advertising.js; alonemode.js; bookmark.js; command.js; followme.js; norecording.js; rememberChannel.js; welcome.js; youtube.js; Youtube_Search.js; YT-search.js

TIME INFORMATION
 - Time (local): 08.03.2019 19:11:55 -03 -03:00:00
 - Time (remote): 08.03.2019 19:11:55 -03 -03:00:00
 - Time (difference): 0 secs (Time diff less than 2 secs. Good.)
 - Timezone: America/Sao_Paulo

OTHER INFORMATION
 - TeamSpeak 3 Version: 3.2.3
 - youtube-dl Version: 2019.03.09
 - DiagScript Version: 0.7.1
==========================================================

**Comment by mxschmitt** [comment]
Hey,

do you have `youtube-dl` correctly installed, so that `!yt` or from the webinterface under `Music` -> `Upload` -> `Download Files` does work without any issues?

For further information: https://sinusbot.github.io/docs/youtube-dl/

(You have to set the YoutubeDLPath)

**Comment by lbenicio** [comment]
manually installed and installed with pip following the link: https://rg3.github.io/youtube-dl/download.html 

but it does not recognises

**Comment by mxschmitt** [comment]
Yep, but you have to adjust the `YoutubeDLPath` in the config.ini.

**Comment by lbenicio** [comment]
such a idiot... reader all over tutorials and did not found... sorry to bother and thank you for the help

everything works fine now! *-*
