### ISSUE TITLE
Die Suche startet nicht

### ISSUE THREAD

**Issue by Messiahs100** [maxibanki/YoutubeWebinterface#3]
An was kann es liegen das er einfach nicht such?

**Comment by mxschmitt** [comment]
It is because the YouTube Key is not correct.
You need a valid YouTube Key.
Be sure that you are using a key with the type Browser. You can try to recreate one, some are partly broken.

**Comment by Messiahs100** [comment]
Hi Max

I use a Browser API Key
<link removed>
Thx for Help!

> It is because the YouTube Key is not correct.
> You need a valid YouTube Key.
> Be sure that you are using a key with the type Browser. You can try to 
> recreate one, some are partly broken.

**Comment by Messiahs100** [comment]
Ah ok i forget a importent part, i dosnt klick on aktivate API for Youtube. Thx man for this awesome script!

**Comment by irgendwr** [comment]
removed link to image to prevent people misusing it
