### ISSUE TITLE
Webserver API Key not working?

### ISSUE THREAD

**Issue by acidbyt3** [maxibanki/YoutubeWebinterface#5]
I'm posting here as a last resort, I've followed every step down to the letter, I've tried looking for help on the forums and google and got  nothing conclusive came up.

I'm picking the API Key for **BROWSER** and followed every step in the tutorial, still can't get it to work.
It always gives me the following error:
YouTube Api Error
Please make sure that you've set a valid api key in the config and enabled the script on the selected instance.

I've made sure the script is activated (and I only have one single instance), the instance is selected in the dropdown box, the key added into the correct field on the script options, I've tried restarting the server as well afterwards, even tried two or three different keys and waited a while after generating the keys (since Google says it can take a few minutes for the changes to take effect).
Am I missing something or is there any chance there might be a bug with the code currently?

Any help with this would be GREATLY appreciated.
I'm running SinusBot 0.9.12.3-36fce3c
Latest YoutubeWebinterface (as of time of writing) here off GitHub

(Edit: The keys are not "Webserver" type, they are "Browser" type. My bad, I typed that wrong here.)

**Comment by acidbyt3** [comment]
**CORRECTION** **They keys are BROWSER type**, not Webserver
Apologies, I typed that in wrong. Here is a screenshot from my Google API page showing the keys type:
https://gyazo.com/471624c7c2380ec4f0323feed6690955

**Comment by irgendwr** [comment]
is your api key 39 characters long?

**Comment by acidbyt3** [comment]
Yes, all 3 keys I tried were exactly 39 characters long.

**Comment by irgendwr** [comment]
are you sure that you've enabled the youtube data api in the google developer console?

**Comment by acidbyt3** [comment]
I am fairly certain, however seeing as this is my first time using API keys, I could be wrong.

IIRC I had to enable the API before I was even able to create them though. Where can I double check this?

**Comment by irgendwr** [comment]
Can I take a quick look over TeamViewer?

**Comment by acidbyt3** [comment]
I believe this is the right place:
https://gyazo.com/d32d15f32fd7e7ded6428c06a59ee8b5

**Comment by acidbyt3** [comment]
Sure, where can I send you the details?

**Comment by irgendwr** [comment]
pn on the forum @ irgendwer

**Comment by acidbyt3** [comment]
Will do, thank you, I really appreciate the help. :)

**Comment by irgendwr** [comment]
np :)

**Comment by irgendwr** [comment]
-- problem solved: weird Browser issue. ^^ --

**Comment by acidbyt3** [comment]
Thanks so much for the help. :) :+1:

**Comment by acidbyt3** [comment]
Figured out the exact cause of the issue: it was a Chrome addon preventing a script from loading. Disabling the plugin fixed the issue.

For future reference, or if anyone ever bumps into a similar issue. Check your addons (or with a different browser altogether) #lessonLearned haha
