### ISSUE TITLE
Youtube api error 

### ISSUE THREAD

**Issue by BloodyMikey** [maxibanki/YoutubeWebinterface#6]
https://puu.sh/rM0nA.png aint this correct way or this ?   https://puu.sh/rM0qE.png

**Comment by irgendwr** [comment]
both are fine but the first is more secure

**Comment by BloodyMikey** [comment]
okay beacuse we still get this https://puu.sh/rM0MU.png

**Comment by irgendwr** [comment]
then use the HTTP referrer option

**Comment by BloodyMikey** [comment]
Should il add my ip there?

**Comment by irgendwr** [comment]
no the url

**Comment by BloodyMikey** [comment]
we do not have a url to the server only a ip

**Comment by BloodyMikey** [comment]
do we need to make a url that directs to our ip

**Comment by irgendwr** [comment]
then try using the IP and if it still doesn't work just use none

**Comment by BloodyMikey** [comment]
None does not work

**Comment by BloodyMikey** [comment]
nor does ip addres

**Comment by BloodyMikey** [comment]
Please make sure that you've set a valid api key in the config and enabled the script on the selected instance.

**Comment by BloodyMikey** [comment]
Schould it be shown in the configs anywhere if it is aktivated

**Comment by BloodyMikey** [comment]
sorry for my bad English here and there

**Comment by irgendwr** [comment]
1) did you reload the page?
2) what errors appear in the browser console? (F12 if you use chrome)

**Comment by BloodyMikey** [comment]
Where schould i see the errors in dev-mode
if there are any

**Comment by BloodyMikey** [comment]
https://puu.sh/rM1re.png

**Comment by irgendwr** [comment]
press F12......

**Comment by BloodyMikey** [comment]
yes i know what f12 is doing

**Comment by BloodyMikey** [comment]
https://puu.sh/rM1uy.png

**Comment by irgendwr** [comment]
go to console

**Comment by BloodyMikey** [comment]
https://puu.sh/rM1we.png

**Comment by mxschmitt** [comment]
reload the page, during the console is open

**Comment by BloodyMikey** [comment]
https://puu.sh/rM1DB.gif

**Comment by irgendwr** [comment]
Okay, can you install TeamViewer and let me take a look at this?

**Comment by BloodyMikey** [comment]
yes

**Comment by BloodyMikey** [comment]
pms then

**Comment by BloodyMikey** [comment]
610 193 426

5912

**Comment by BloodyMikey** [comment]
there when you are on we change pass so noone els is on

**Comment by BloodyMikey** [comment]
inside the sinusbot configs we cannot even se it about youtube we inteface is there

**Comment by BloodyMikey** [comment]
should it?

**Comment by irgendwr** [comment]
yes, script settings do not get saved there

**Comment by BloodyMikey** [comment]
okay where is that saved if it does not save there then its a problem

**Comment by irgendwr** [comment]
thats not really the problem, the web page is not able to get the script config, this might be an issue with some chrome addon (maybe adblock?). we had something like that before (caused by some blocking addon).

**Comment by BloodyMikey** [comment]
i have disabled addblock incase this was a problem but nothing changed

**Comment by zotec78** [comment]
same issue over here guys.
I did all right but it isn't working

**Comment by mxschmitt** [comment]
Please create a new issue with an detailed error description

**Comment by JonasBoegle** [comment]
@BloodyMikey @zotec78 can you create a sinusbot user w/ no privileges and send me the login details and a link to your webinterface so that I can look into this issue? Thanks! (dev@sandstorm-projects.de)

**Comment by irgendwr** [comment]
**Update**: This Error seems to be caused by a bug in the unstable pre-release Sinusbot Version 0.9.15 so sadly there is nothing we can do about it atm.
